server:
  port: 8090
spring:
  application:
    name: springsecurity
  datasource:
    url: jdbc:mysql://localhost:3306/user?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  thymeleaf:
    prefix: classpath:/public/
    suffix: .html
    mode: HTML5
    encoding: utf-8
    cache: false
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.wb.security.domian


