stages:
  - edge
  - pages

pages:
  stage: pages
  script:
    - testing-java
  artifacts:
    paths:
      - public

edge:
  stage: edge
  script:
    - OCP_PROJECT=d4i-edge-admin ocp-build
  only:
    - "dev"