stages:
  - edge
  - pages

pages:
  stage: pages
  script:
    - mvn -B clean package
    - testing-java
    - cp -R target/asciidoc/html ./public
  artifacts:
    paths:
      - public

edge:
  stage: edge
  script:
    - OCP_PROJECT=d4i-edge ocp-build
    - OCP_PROJECT=d4i-edge-admin ocp-build
  only:
    - "dev"