stages:
  - edge
  - release
  - pages

pages:
  stage: pages
  script:
    - mvn -B clean package
    - testing-java
    - cp -R target/asciidoc/html ./public
  artifacts:
    paths:
      - public
  only:
    - "1.0"

edge:
  stage: edge
  script:
    - OCP_PROJECT=d4i-edge ocp-build
  only:
    - "1.0"

dev:
  stage: dev
  script:
    - OCP_PROJECT=d4i-dev ocp-build
  only:
    - "dev"

release:
  stage: release
  script:
    - OCP_PROJECT=d4i ocp-build
  only:
    - "master"