server:
  port: 5273
spring:
  application:
    name: PROJECT_NAME
  data:
    mongodb:
      uri: ${mongodb.uri:mongodb://172.25.2.31:27017/start}
  jackson:
    serialization:
      INDENT_OUTPUT: true